services:
  postgres:
    container_name: fundamentos-backend-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fudamentos-backend
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  nestjs:
    container_name: trabalho-docker-fundamentosbackend
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && node dist/main"]
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - nestjs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf